# Generated by Django 3.2.9 on 2021-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(max_length=1200)),
                ('timestamp', models.DateTimeField()),
                ('is_validated', models.BooleanField(default=False)),
                ('has_errors', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
