# Generated by Django 3.2.9 on 2021-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='has_errors',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='data',
            field=models.CharField(max_length=1200),
        ),
    ]
