# Generated by Django 3.2.9 on 2021-11-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0002_auto_20211122_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='raweventsdata',
            name='data',
            field=models.CharField(default='data', max_length=2000),
            preserve_default=False,
        ),
    ]
