# Generated by Django 3.2.9 on 2021-11-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_eye', '0003_raweventsdata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=250)),
                ('session_id', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_description', models.CharField(max_length=250)),
                ('raw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_eye.raweventsdata')),
            ],
        ),
    ]
